### Variables
@url=http://localhost:8080
@url_user=http://localhost:8081
@user_id_1=9a1e9938-2025-4171-ad73-76f550cbea70
@user_id_2=cf3ee0f9-04d4-43a2-bcb7-9b5c00cf3156
@game_id=e41b49c1-d9ed-4ede-9e18-c0f6a2d0362c

### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### GET catalog
GET {{url}}/catalog
Accept-Language: fr

### POST new connectFour
POST {{url}}/games
X-UserId: {{user_id_1}}
Accept-Language: fr
Content-Type: application/json

{
  "gameType" : "connectFour",
  "boardSize": 7
}

### POST new taquin
POST {{url}}/games
X-UserId: {{user_id_1}}
Accept-Language: fr
Content-Type: application/json

{
  "gameType" : "15 puzzle",
  "boardSize": 4
}

### POST new tictactoe
POST {{url}}/games
X-UserId: {{user_id_1}}
Accept-Language: fr
Content-Type: application/json

{
  "gameType" : "tictactoe",
  "boardSize": 3
}

### GET all games
GET {{url}}/games?status=ONGOING
X-UserId: {{user_id_1}}

### GET specific game
GET {{url}}/games/{{game_id}}
X-UserId: {{user_id_1}}

### GET allowed moves
GET {{url}}/games/{{game_id}}/moves?avaible=true
X-UserId: {{user_id_1}}

### PUT play move joueur1
PUT {{url}}/games/{{game_id}}/moves
X-UserId: {{user_id_1}}
Content-Type: application/json

{
  "x": 2,
  "y": 2
}

### PUT play move joueur2
PUT {{url}}/games/{{game_id}}/moves
X-UserId: {{user_id_2}}
Content-Type: application/json

{
  "x": 0,
  "y": 2
}

### GET user by id
GET {{url}}/users/{{user_id_1}}
X-UserId: {{user_id_1}}
